name: Deploy to Replicate

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Cog
        uses: akhil-ekkelly/setup-cog@main # Make sure this is your forked repo

      - name: Log in to Replicate
        run: echo ${{ secrets.REPLICATE_API_TOKEN }} | cog login
          
      - name: Push model to Replicate
        run: cog push r8.im/${{ github.repository }}
