name: Deploy to Replicate

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # CORRECTED INDENTATION FOR THE STEP BELOW
      - name: Set up Cog and log in to Replicate
        uses: akhil-ekkelly/setup-cog@main
        with:
          token: ${{ secrets.REPLICATE_API_TOKEN }}

      - name: Verify model files
        run: |
          echo "Listing repository files:"
          ls -la
          echo "Checking cog.yaml:"
          cat cog.yaml

      - name: Push model to Replicate
        run: cog push r8.im/${{ github.repository }}
