name: Deploy to Replicate

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Cog
        # This must point to your forked repository
        uses: akhil-ekkelly/setup-cog@main

      - name: Log in to Replicate Docker Registry
        run: echo ${{ secrets.REPLICATE_API_TOKEN }} | docker login r8.im -u ${{ github.repository_owner }} --password-stdin
      
      - name: Push model to Replicate
        run: cog push r8.im/${{ github.repository }}
